Add replication to the concepts and the reference guide section
memgraph/docs pull request #121
Opened 2021-01-25 14:21 UTC by the-joksim

* broken up the replication feature spec into the `Concepts` and `Reference guide` files

2021-01-25 14:54 UTC, antonio2368 commented on products/memgraph/upcoming/reference_guide/replication.md
> +replication port as the main, a semantic exception will be thrown.
Semantic exception doesn't mean much to the user I think? Maybe just note that it's not valid and the query will fail.

2021-01-25 14:54 UTC, antonio2368 commented on products/memgraph/upcoming/reference_guide/replication.md
> +enable replication in the main instance by issuing the following openCypher
This isn't openCypher but our own?

2021-01-25 14:54 UTC, antonio2368 commented on products/memgraph/upcoming/reference_guide/replication.md
> +SET REPLICATION ROLE TO (MAIN|REPLICA) WITH PORT <port_number>;
`SET REPLICATION ROLE TO (MAIN|REPLICA)  [WITH PORT <port_number>];`?

2021-01-28 15:40 UTC, gitbuda requested changes

2021-01-28 15:40 UTC, gitbuda commented on products/memgraph/upcoming/concepts/replication.md
> +to this rule and is described below). Replicas can also be configured to be
There is no support for the replicas of replicas yet (under Limitations). I would remove it from here to avoid confusion.

2021-01-28 15:40 UTC, gitbuda commented on products/memgraph/upcoming/reference_guide/replication.md
> +allows the cluster to be dynamically rearranged (new leader election, addition
Instead of `new leader election` use something similar to `changing the main instance`...

2021-01-28 18:10 UTC, closed without merging