update-concepts
memgraph/docs pull request #267
Opened 2021-12-20 13:35 UTC by vpavicic

[x] went through concept pages and made language changes

2021-12-20 13:56 UTC, kgolubic commented on docs/concepts/indexing.md
>  ```
Add one empty line after this line.

2021-12-20 13:56 UTC, kgolubic commented on docs/concepts/indexing.md
>  ```cypher
Add one empty line before this line.

2021-12-20 14:12 UTC, kgolubic commented on docs/concepts/storage.md
> +You can also generate a snapshot file by using Memgraph's import tools. For more
I'm not sure if snapshots generated by import tools fall into this category. Can you please double-check this?

2021-12-20 14:17 UTC, kgolubic commented on docs/concepts/storage.md
>  ```
Add an empty line before this one.

2021-12-20 14:19 UTC, kgolubic commented on docs/concepts/storage.md
>  ```
Add one empty line before this line.

2021-12-20 14:19 UTC, kgolubic commented on docs/concepts/storage.md
>  ```
Add one empty line after this line.

2021-12-20 14:20 UTC, kgolubic requested changes
I've left a few comments. Most of them are related to formatting issues.

2021-12-20 14:26 UTC, vpavicic commented on docs/concepts/graph-algorithms.md
> +internally used by Memgraph. We believe that advanced users could significantly
Maybe advanced users are still not using them as much as they could... I'm not sure what is implied... will ask in the channel

2021-12-22 13:40 UTC, kgolubic commented on docs/concepts/graph-algorithms.md
> +all a part of [MAGE](/mage/overview.md).
URL for MAGE needs to be fixed.

2021-12-22 13:50 UTC, kgolubic approved these changes

2021-12-22 13:52 UTC, merged