[master < T0614-DX] Replication documentation
memgraph/docs pull request #340
Opened 2022-03-31 10:49 UTC by vpavicic

- [ ] Reference guide
- [ ] Under the hood
- [ ] How to guide

Additional changes
- [x] Add query for showing users

2022-04-08 10:46 UTC, g-despot commented
The content looks great and everything is much better described than before.
Two general comments:
- Include images if possible. Either from the replication blog post or you can request new ones from our designers. We are generally not using enough images in our docs.
- Cross-link between the how-to guide, reference guide and under the hood page. For example, you can link the replication modes from the under the hood page in the reference guide as they are described in more detail there.

2022-04-08 10:48 UTC, g-despot requested changes
- Add images if possible.
- Cross-link between the pages where it's applicable and helpful.

2022-04-11 07:11 UTC, vpavicic commented
Image issues: 

I don't believe its efficient to add images until we know the explanation is 100% correct
Some of the images used in the blog were... confusing to me (even Buda) so I can't just recycle and I need to know that everything is 100% correct - bcs it's easier to correct the text than images i would merge this without images, if buda doesn't review in 2 weeks, i'll add the images based on this text... i can prepare images and just add them in 2 weeks

Linking - OK

2022-04-21 11:51 UTC, g-despot approved these changes

2022-04-21 11:52 UTC, merged