[master<T0634] Lab features regarding query modules
memgraph/docs pull request #364
Opened 2022-04-14 07:23 UTC by vpavicic

- [x] add that you can create QM from Lab + pictures
- [x] add labels

2022-04-19 13:50 UTC, katarinasupe commented
I added a couple of minor fixes, but I think this is not done because we need to fix the part about default query modules directories. I think it's not possible to change the location for `internal_modules` directory, that is, the location where Memgraph Lab will store procedures to and load procedures from. You can only define new query module directory/directories via `--query-modules-directory` flag, where you can manually save new procedures. 

As I see it, `internal_modules` is always the same, located at `/var/lib/memgraph/internal_modules` and you are not creating it. On the other hand, `query_modules` directory is the default one for all procedures that you get with MAGE, but if you want Memgraph to check some other folder when loading procedures, you can add it via `--query-modules-directory`. For example, you can create new folder called `my_query_modules` and then add it via flag: `--query-modules-directory=/usr/lib/memgraph/query_modules, /usr/lib/memgraph/my_query_modules`.

Ping me and we can discuss this and merge this PR 😄

2022-04-19 13:53 UTC, katarinasupe requested changes
I added a couple of minor fixes, but I think this is not done because we need to fix the part about default query modules directories. I think it's not possible to change the location for `internal_modules` directory, that is, the location where Memgraph Lab will store procedures to and load procedures from. You can only define new query module directory/directories via `--query-modules-directory` flag, where you can manually save new procedures. 

As I see it, `internal_modules` is always the same, located at `/var/lib/memgraph/internal_modules` and you are not creating it. On the other hand, `query_modules` directory is the default one for all procedures that you get with MAGE, but if you want Memgraph to check some other folder when loading procedures, you can add it via `--query-modules-directory`. For example, you can create new folder called `my_query_modules` and then add it via flag: `--query-modules-directory=/usr/lib/memgraph/query_modules, /usr/lib/memgraph/my_query_modules`.

Ping me and we can discuss this and merge this PR 😄

2022-04-25 08:45 UTC, vpavicic commented
> 
I tried to address this, but if this is not enough, I'm not sure what exactly you are proposing :)

2022-05-04 14:28 UTC, g-despot approved these changes

2022-05-04 14:30 UTC, merged