[master<677-1] Add overview page for import
memgraph/docs pull request #855
Opened 2023-04-27 10:56 UTC by vpavicic

### Description

Please briefly explain the changes you made here.

### Pull request type

Please delete options that are not relevant and check the ones that are.

- [ ] Documentation fix
- [ ] New documentation page 
- [ ] Base PR for the release
- [x] Documentation improvements
- [ ] Other (please describe):

2023-04-28 13:22 UTC, katarinasupe requested changes
I see that you ditched the native/client idea, but I still like it. I think it is a good starting point and we can iterate later if we notice something that can be changed. Btw. some of the links are bolded, some are not, maybe unify that?

2023-04-28 13:22 UTC, katarinasupe commented on docs/import-data/overview.md
> +file from a local file  from a remote address.
```suggestion
file from a local file and from a remote address.
```

2023-04-28 13:26 UTC, katarinasupe commented
Forgot to mention, one thing missing here - tip for fastest import. You can do similar to what I wrote in GQLA for now, and we will expand LOAD CSV subpage with ANALYTICAL MODE. https://github.com/memgraph/docs/pull/841/files#diff-20ae718e9607aa84472b93127370f5721e866009efb54b937fdb805d4738e872R19

2023-05-02 13:07 UTC, vpavicic commented on docs/import-data/overview.md
> +You can also use [`import_util.json` procedure](/import-data/files/load-json.md)
```suggestion
You can also use [**`import_util.json` procedure**](/import-data/files/load-json.md)
```

2023-05-02 13:08 UTC, vpavicic commented on docs/import-data/overview.md
> +into Memgraph [using GQLAlchemy](/gqlalchemy/how-to-guides/table-to-graph-importer).
```suggestion
If you are a Python user you can import **Parquet**, **ORC** or **IPC/Feather/Arrow** file
into Memgraph [using **GQLAlchemy**](/gqlalchemy/how-to-guides/table-to-graph-importer).
```

2023-05-02 13:10 UTC, vpavicic commented on docs/import-data/overview.md
>  [here](/connect-to-memgraph/drivers/overview.md).
```suggestion
Memgraph offers a [**wide range of clients**](/connect-to-memgraph/drivers/overview.md) that can be used to connect directly to the platform and import data.
```

2023-05-02 13:11 UTC, vpavicic commented on docs/import-data/overview.md
> +You can import the JSON file into Memgraph by using the [**`json-util` query
```suggestion
You can import the **JSON** file into Memgraph by using the [**`json-util` query
```

2023-05-02 13:52 UTC, katarinasupe commented
Fix broken links and ship it 🚀

2023-05-03 07:26 UTC, merged