docker-changes
memgraph/docs pull request #917
Opened 2023-06-09 07:42 UTC by vpavicic

### Description

I've added some info about how the Memgraph environment looks like in Docker image

### Pull request type

Please delete options that are not relevant and check the ones that are.

- [ ] Documentation fix
- [ ] New documentation page 
- [ ] Base PR for the release
- [x] Documentation improvements
- [ ] Other (please describe):

### Related PRs and issues

Closes #860

### Checklist:

- [ ] I checked all content with Grammarly
- [ ] I performed a self-review of my code
- [ ] I made corresponding changes to the rest of the documentation
- [ ] The build passes locally
- [ ] My changes generate no new warnings or errors

2023-06-13 07:06 UTC, antejavor requested changes
Except for the comments, take a look at the paths, we are mixing the Windows and Linux paths, lines 120 - 140.

2023-06-15 07:55 UTC, vpavicic commented on docs/how-to-guides/work-with-docker.md
>  Specifying a volume creates a copy of a directory inside the Docker container as
```suggestion
Specifying a volume syncs the specified directory inside the Docker container as
```

2023-06-15 07:59 UTC, vpavicic commented on docs/how-to-guides/work-with-docker.md
> +
```suggestion

Bind mounts do not handle data permissions which could cause issues with permissions. 
```

2023-06-15 08:06 UTC, vpavicic commented
> Except for the comments, take a look at the paths, we are mixing the Windows and Linux paths, lines 120 - 140.

I will open a new issue for this because i need to fix it at many places and need to think about it a bit, how to handle it :)

2023-06-20 06:36 UTC, merged