[master<]
memgraph/docs pull request #948
Opened 2023-06-28 12:15 UTC by vpavicic

### Description

Changelog for MAGE v.1.8.0

2023-06-30 11:49 UTC, vpavicic commented on mage/changelog.md
> +## v1.8.0 - Jun 28, 2023
```suggestion
## v1.8.0 - Jun 30, 2023
```

2023-07-20 14:45 UTC, antoniofilipovic commented on mage/changelog.md
> +- The `migration` module has an option to get data from MySQL, SQL server, or
`migrate` module

2023-07-20 14:45 UTC, antoniofilipovic requested changes
only migrate module is wrongly called

2023-07-21 09:47 UTC, vpavicic commented on mage/changelog.md
> +- The `migration` module has an option to get data from MySQL, SQL server, or
```suggestion
- The `migrate` module has the option to get data from MySQL, SQL server, or
```

2023-07-21 10:45 UTC, merged