[master<] Changelog for Lab 2.7.1
memgraph/docs pull request #962
Opened 2023-07-05 11:50 UTC by vpavicic

### Description

Created a changelog for Lab 2.7.1

2023-07-05 15:13 UTC, cizl requested changes
We added 2 more fixes:

* Query execution choice now closes on click as expected.
* Fixed bug and improved behavior when running a query that has style errors.

And
* Renamed System Default Style to System Style.

2023-07-06 08:25 UTC, cizl approved these changes
Nice! :fire:

2023-07-06 10:04 UTC, vpavicic commented on lab/changelog.md
> +  decide to run it with the System Style.
```suggestion
  decide to run it using the System Style. 
```

2023-07-06 10:05 UTC, vpavicic commented on lab/changelog.md
> +- If you run a query that has errors in the Graph Style Script code you can
```suggestion
- If you run a query that has errors in the Graph Style Script code, you can
```

2023-07-06 12:16 UTC, merged